name : Push except on staging

on: 
  push: 
    branches-ignore: #tout passe sauf staging
        - 'staging'

jobs: 
  build-test: 
    runs-on: ubuntu-latest 

    steps: 
      - name: Print the current time
        run: |
          echo $(date)