name : Pull request open

on: 
  pull_request: 
    types: [open]
  #schedule : 
  #toute les 5 minutes
  #*/5 * * * *
  #toutes les 3 heures
  #-cron: '0 0-21/3 * * *'
  #-cron: '30 1-22/3 * * *'      

jobs: 
  build-test: 
    runs-on: ubuntu-latest 

    steps: 
      - name: Print the current time
        run: |
          echo $(date)