name : Push on dev

on: 
  push: 
    branches: ["dev"]
        

jobs: 
  build-test: 
    runs-on: ubuntu-latest 

    steps: 
      - name: Print the current time
        run: |
          echo $(date)

