name : Push on specific folder

on: 
  push: 
    paths: #tout passe sauf staging
        - 'specific-folder/**'

jobs: 
  build-test: 
    runs-on: ubuntu-latest 

    steps: 
      - name: Print the current time
        run: |
          echo $(date)