name : Push on feat/

on: 
  push: 
    branches: #tout passe sauf staging
        - feat/**


jobs: 
  build-test: 
    runs-on: ubuntu-latest 

    steps: 
      - name: Print the current time
        run: |
          echo $(date)