name : Push on dev

on: 
  push: 
    paths: 
        - '**.ts'

jobs: 
  build-test: 
    runs-on: ubuntu-latest 

    steps: 
      - name: Print the current time
        run: |
          echo $(date)